# fly.toml app configuration file generated for wreckless-multiplayer on 2025-07-18T09:26:30-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wreckless-multiplayer'
primary_region = 'ord'

[build]
  builder = 'paketobuildpacks/builder:base'
  buildpacks = ['paketo-buildpacks/nodejs']

[deploy]
  release_command = "echo 'Starting Wreckless Multiplayer Server'"

[env]
  NODE_ENV = 'production'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
